name: fontra
title: Fontra Pak (Unofficial snap package)
base: core24 # the base snap is the execution environment for this snap
summary: Browser-based variable-first font editor # 79 char long summary
description: |
  Fontra is an open-source, browser-based, cross-platform, variable-first
  font editor. Fontra extends the boundaries of what current font editors
  can do. Originally developed to make the design and production of large
  CJK fonts more efficient, Fontra provides deeper integration of variable
  font technology and improved usability of variable components as design
  elements.

grade: stable
confinement: strict
adopt-info: fontrapak
platforms:
  amd64:
    build-on: amd64
    build-for: amd64

parts:
  fontrapak:
    plugin: python  # Use the Python plugin
    source: .
    python-requirements:
      - requirements.txt
    build-packages:
      - nodejs
      - npm
      - git
    stage-packages:
      - libgl1
      - libegl1
      - libxcb-cursor0
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcb-randr0
      - libxcb-xfixes0
      - libxkbcommon0
      - libqt6gui6
      - libqt6core6
      - libqt6widgets6
      - libstdc++6
      - libpulse0          # For PulseAudio
      - libatomic1         # For atomic operations
      - libwayland-cursor0 # For Wayland
      - libwayland-egl1    # For Wayland EGL
    override-build: |
      # Verify the Node.js and npm versions
      node -v
      npm -v

      # Install npm dependencies
      npm install

      # Proceed with the default Python build process
      craftctl default
      # Step to create version from fontra  
      echo $(python3 -c "import fontra; print(fontra.__version__)") > ./version.txt
      VERSION_FROM_FILE=$(cat version.txt | tr -d '\n')
      craftctl set version="$VERSION_FROM_FILE"

icon: snap/gui/fontrapak.svg
license: GPL-3.0+

plugs:
  shared-memory:
    private: true

apps:
  fontrapak:
    command: bin/python3 FontraPakMain.py
    environment:
      QT_QPA_PLATFORM: xcb  
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt6/plugins/platforms # Explicitly set plugin path
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa # Include Mesa libraries if needed
    plugs:
      - x11
      - unity7
      - opengl
      - network # if any network access is needed
      - home # if it needs access to user home directory
      - removable-media # if it needs access to removable media.
      - desktop
      - desktop-legacy
      - wayland # for wayland support
