name: Build and Upload Artifact
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "21 1 * * 1-5"
  workflow_dispatch: # allow manual trigger
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]


jobs:
  build-ubuntu-binary:
    runs-on: ubuntu-22.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Build exe
        run: |
          pyinstaller FontraPak.spec -y
          mv dist/Fontra\ Pak dist/fontrapak

      - name: Run tests
        run: |
          pytest

      - name: Query __version__ string and add to version.txt
        id: query-version
        run: |
          echo $(python -c "import fontra; print(fontra.__version__)") > ./dist/version.txt
      - name: Storing Ubuntu Artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: fontrapak
          path: ./dist/*
  upload-to-download-server:
    runs-on: ubuntu-22.04
    needs: [build-ubuntu-binary]
    if: github.ref == 'refs/heads/main'

    steps:

      - name: Retrieve Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./dl
      - name: make binary executable
        run: chmod +x ./dl/fontrapak/fontrapak
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./dl
      - name: tar gzip file
        run: |
          cd ./dl
          tar -czvf fontrapak.tgz "fontrapak"

      - name: Upload via ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
           host: ftp.atipra.in
           user: ${{ secrets.FTP_USERNAME }}
           password: ${{ secrets.FTP_PASSWORD }}
           localDir: "dl"
           remoteDir: "public_html/fonts/fontrapak"
           forceSsl: true
