name: Build and Upload Artifact
on:
  push:
    branches:
      - main

jobs:
  build-ubuntu-binary:
    runs-on: ubuntu-22.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Build exe
        run: |
          pyinstaller FontraPak.spec -y
          mv dist/Fontra\ Pak dist/fontrapak

      - name: Run tests
        run: |
          pytest

      - name: Storing Ubuntu Artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: fontrapak
          path: ./dist/*
  upload-to-download-server:
    runs-on: ubuntu-22.04
    needs: [build-ubuntu-binary]
    if: github.ref == 'refs/heads/main'

    steps:

      - name: Retrieve Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./dl

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./dl

      - name: Upload via ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "dl"
          remoteDir: "fontrapak"
          forceSsl: true

