name: Build Application

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "21 1 * * 1-5"
  workflow_dispatch: # allow manual trigger
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build-ubuntu-binary:
    runs-on: ubuntu-22.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Build exe
        run: |
          pyinstaller FontraPak.spec -y
          mv dist/Fontra\ Pak dist/fontrapak

      - name: Run tests
        run: |
          pytest

      - name: Storing Ubuntu Artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: fontrapak
          path: ./dist/*
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
        path: /bin
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating fontrapak app"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
